INSERT INTO libri SET titolo = 'L'ombra del vento', pagine = 567, prezzo = 567, editore_id = 1';
INSERT INTO libri SET titolo = 'Il nome della rosa', pagine = 512, prezzo = 512, editore_id = 1';
INSERT INTO libri SET titolo = '1984', pagine = 328, prezzo = 328, editore_id = 1';
INSERT INTO libri SET titolo = 'Il piccolo principe', pagine = 96, prezzo = 96, editore_id = 1';
INSERT INTO libri SET titolo = 'Orgoglio e pregiudizio', pagine = 352, prezzo = 352, editore_id = 1';
INSERT INTO libri SET titolo = 'Harry Potter e la pietra filosofale', pagine = 309, prezzo = 309, editore_id = 1';
INSERT INTO libri SET titolo = 'Il grande Gatsby', pagine = 180, prezzo = 180, editore_id = 1';
INSERT INTO libri SET titolo = 'Il ritratto di Dorian Gray', pagine = 256, prezzo = 256, editore_id = 1';
INSERT INTO libri SET titolo = 'Il signore degli anelli', pagine = 1248, prezzo = 1248, editore_id = 1';
INSERT INTO libri SET titolo = 'La casa degli spiriti', pagine = 448, prezzo = 448, editore_id = 1';
INSERT INTO libri SET titolo = 'Cent'anni di solitudine', pagine = 432, prezzo = 432, editore_id = 1';
INSERT INTO libri SET titolo = 'La solitudine dei numeri primi', pagine = 304, prezzo = 304, editore_id = 1';
INSERT INTO libri SET titolo = 'Anna Karenina', pagine = 864, prezzo = 864, editore_id = 1';
INSERT INTO libri SET titolo = 'Il cacciatore di aquiloni', pagine = 391, prezzo = 391, editore_id = 1';
INSERT INTO libri SET titolo = 'Don Chisciotte della Mancia', pagine = 928, prezzo = 928, editore_id = 1';
INSERT INTO libri SET titolo = 'La fattoria degli animali', pagine = 141, prezzo = 141, editore_id = 1';
INSERT INTO libri SET titolo = 'Dracula', pagine = 488, prezzo = 488, editore_id = 1';
INSERT INTO libri SET titolo = 'Viaggio al centro della Terra', pagine = 284, prezzo = 284, editore_id = 1';
INSERT INTO libri SET titolo = 'Moby Dick', pagine = 720, prezzo = 720, editore_id = 1';
INSERT INTO libri SET titolo = 'I promessi sposi', pagine = 712, prezzo = 712, editore_id = 1';
